### ISSUE TITLE
Requesting support with error "Explicit 'name separator' in class"

### ISSUE THREAD

**Issue by josruirod** [fmalmeida/MpGAP#42]
Hi,

Thanks for your kind support in the past. I've been using mpgap routinely in our projects, but now I've been struggling for a while with a new installation... maybe trivial but I'm stuck and wondered if you could comment on it. 
I'm using singularity. Everything seems to be working, and the pipeline starts, but then ends with the error:

> Explicit 'name separator' in class near index 8
> [dataset/pacbio.fastq]
>         ^
>  -- Check script '/.nextflow/assets/fmalmeida/mpgap/./workflows/parse_samples.nf' at line: 66 or see '.nextflow.log' file for more details
> 

I believe I've used the same syntax as always, and the one suggested in the manual in the yml samplesheet:
samplesheet:

>   - id: Sol_test_1
>     pacbio: 
>       - 'dataset/pacbio.fastq'
>     genome_size: 39.11m
>     wtdbg2_technology: rs
>     corrected_long_reads: false  

I'm attaching the [nextflow.log](https://github.com/fmalmeida/MpGAP/files/10570094/nextflow.log). May be something trivial and nextflow-related... but could you comment please? I've unsuccesfully tried to use different quotes in the yml file, or even placing the file on the same folder. 

Thanks!

**Comment by fmalmeida** [comment]
Hi @josruirod ,
Thanks for using the tool. I am a bit busy recently but I can give it a try tonight.

could you share with me the yml file you’re using? Not just copy and paste but the file itself? So I can download some pacbio data and try with it to see if I can reproduce.

but indeed, sounds that for some reason it is not parsing correctly 

😬

**Comment by fmalmeida** [comment]
Before I actually try, I saw two things:

You have like this:

```yaml
- id: Sol_test_1
  pacbio: 
    - 'dataset/pacbio.fastq'
  genome_size: 39.11m
  wtdbg2_technology: rs
  corrected_long_reads: false 
```

but the line breaked syntax is used for Illumina that can expect SE, PE or both reads. As long reads is always one, I think I wrote to expect in one line:

```yaml
- id: Sol_test_1
  pacbio: dataset/pacbio.fastq
  genome_size: 39.11m
  wtdbg2_technology: rs
  corrected_long_reads: false 
```

Also, I think is best that in the samplesheet you use the absolute paths to files to avoid the pipeline not finding it :)
